/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import java.awt.Font;

import tio.Tio;

/**
 *
 * @author rodol_000
 */
public class FrameTiogotchi extends javax.swing.JFrame {

    /**
     * Creates new form FrameTiogotchi
     */
	Tio tio;
	public static final int HUMOR_FELIZ = 0;
	public static final int HUMOR_OK    = 1;
	public static final int HUMOR_TRISTE = 2;
	public static final int HUMOR_FAMINTO = 3;
	public static final int HUMOR_MORTO   = 4;
	
	public int humor;
    public FrameTiogotchi() {
        initComponents();
        setHumor(HUMOR_OK);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comer = new javax.swing.JButton();
        dormir = new javax.swing.JButton();
        exercitar = new javax.swing.JButton();
        energiaProgressBar = new javax.swing.JProgressBar(0, 100);
        jLabel1 = new javax.swing.JLabel();
        saudeProgressBar = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        canvas1 = new java.awt.Canvas();
        humorLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        comer.setText("Comer");
        comer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comerMouseClicked(evt);
            }
        });
        comer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comerActionPerformed(evt);
            }
        });

        dormir.setText("Dormir");
        dormir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dormirMouseClicked(evt);
            }
        });
        dormir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dormirActionPerformed(evt);
            }
        });

        exercitar.setText("Exercitar");
        exercitar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exercitarMouseClicked(evt);
            }
        });
        exercitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exercitarActionPerformed(evt);
            }
        });

        energiaProgressBar.setOrientation(1);

        jLabel1.setText("Energia");

        saudeProgressBar.setOrientation(1);

        jLabel2.setText("Saude");

        humorLbl.setText(":)");
        Font inuse = humorLbl.getFont();
        inuse = new Font(inuse.getName(), inuse.getStyle(), inuse.getSize()*10);
        humorLbl.setFont(inuse);
        //jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/tiotriste.png"))); // NOI18N



        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(comer)
                        .addGap(42, 42, 42)
                        .addComponent(dormir)
                        .addGap(35, 35, 35)
                        .addComponent(exercitar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1)
                        .addGap(261, 261, 261)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(energiaProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(humorLbl)
                        .addGap(32, 32, 32)
                        .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(saudeProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()))));
        
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(energiaProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(humorLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(saudeProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comer)
                    .addComponent(dormir)
                    .addComponent(exercitar))
                .addGap(220, 220, 220))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_comerMouseClicked

    private void dormirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dormirMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dormirMouseClicked

    private void exercitarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exercitarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_exercitarMouseClicked

    private void comerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comerActionPerformed

    private void dormirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dormirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dormirActionPerformed

    private void exercitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exercitarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exercitarActionPerformed

    private void estadoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoButtonActionPerformed

    private void energiaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_energiaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_energiaButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    public void setEnergiaLvl(double lvl){
    	
    	this.energiaProgressBar.setValue((int) lvl);
    }
    public void setTio(Tio tio){
    	this.tio = tio;
    }
    public void setHumor(int humor){
    	this.humor = humor;
    	Color color = null;
    	String cara = "{|:{)";
    	switch(humor){
    	
    		case HUMOR_FELIZ:
    			color = Color.decode("#ddffe0");
    			
    			cara  = ":)";
    			break;
    		case HUMOR_OK:
    			color = Color.decode("#dddeff");
    			cara  = ":|";
    			break;
    		case HUMOR_FAMINTO:
    			color = Color.decode("#ffdddd"); 
    			cara  = ":&";
    			break;
    		case HUMOR_TRISTE:
    			color = Color.decode("#f9ddff"); 
    			cara  = ":(";
    			break;
    		case HUMOR_MORTO:
    			color = Color.decode("#d2d2d2");
    			cara  = ":x";
    			break;    
    	}
    	energiaProgressBar.setForeground(color);
    	humorLbl.setText(cara);
    	getContentPane().setBackground(color);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Canvas canvas1;
    private javax.swing.JButton comer;
    private javax.swing.JButton dormir;
    private javax.swing.JButton exercitar;
    private javax.swing.JProgressBar energiaProgressBar;    
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel humorLbl;
    private javax.swing.JProgressBar saudeProgressBar;
    // End of variables declaration//GEN-END:variables
}
